### ISSUE TITLE
Service watcher stops on consul disconnect

### ISSUE THREAD

**Issue by holycheater** [devopsftw/vergilius#7]
```
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/vergilius/vergilius/models/certificate.py", line 46, in watch
    yield self.tc.kv.get('vergilius/certificates/%s/' % self.service.id, index=index, recurse=True)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/consul/tornado.py", line 42, in _request
    raise gen.Return(callback(self.response(response)))
  File "build/bdist.linux-x86_64/egg/consul/base.py", line 186, in cb
    CB.__status(response, allow_404=allow_404)
  File "build/bdist.linux-x86_64/egg/consul/base.py", line 143, in __status
    raise ConsulException("%d %s" % (response.code, response.body))
ConsulException: 500 No cluster leader
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/vergilius/vergilius/loop/service_watcher.py", line 20, in watch_services
    index, data = yield vergilius.consul_tornado.catalog.services(index, wait=None)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/consul/tornado.py", line 42, in _request
    raise gen.Return(callback(self.response(response)))
  File "build/bdist.linux-x86_64/egg/consul/base.py", line 186, in cb
    CB.__status(response, allow_404=allow_404)
  File "build/bdist.linux-x86_64/egg/consul/base.py", line 143, in __status
    raise ConsulException("%d %s" % (response.code, response.body))
ConsulException: 500 rpc error: unexpected EOF
```

**Comment by bazilio91** [comment]
One more fail that stops watcher:

```
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/vergilius/vergilius/loop/service_watcher.py", line 20, in watch_services
    index, data = yield vergilius.consul_tornado.catalog.services(index, wait=None)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/consul/tornado.py", line 37, in _request
    response = yield self.client.fetch(request)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by holycheater** [comment]
another one

```
INFO:vergilius:[service watcher]: new service: ${SERVICE_API}
INFO:vergilius:[service][${SERVICE_API}]: new and loading
nginx: [emerg] directive "server_name" is not terminated by ";" in /tmp/tmpUFK3FV:12
nginx: configuration file /tmp/tmpC8QyNX test failed
ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/opt/vergilius/vergilius/loop/service_watcher.py", line 21, in watch_services
    self.check_services(data)
  File "/opt/vergilius/vergilius/loop/service_watcher.py", line 31, in check_services
    self.services[service_name] = Service(service_name)
  File "/opt/vergilius/vergilius/models/service.py", line 34, in __init__
    self.fetch()
  File "/opt/vergilius/vergilius/models/service.py", line 39, in fetch
    self.parse_data(data)
  File "/opt/vergilius/vergilius/models/service.py", line 88, in parse_data
    self.flush_nginx_config()
  File "/opt/vergilius/vergilius/models/service.py", line 99, in flush_nginx_config
    if not self.validate():
  File "/opt/vergilius/vergilius/models/service.py", line 149, in validate
    os.unlink('%s.pid' % service_config_file.name)
OSError: [Errno 2] No such file or directory: '/tmp/tmpUFK3FV.pid'
INFO:vergilius:[service][${SERVICE_API}]: deleting
```
